language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php -v
  - ./vendor/bin/phpcs --standard=psr2 DependencyInjection/ EventListener/ Provider/ Tests/SymfonyRollbarBundle
  - ./vendor/bin/phpunit -c Tests/phpunit.xml.dist

after_success:
    - bash <(curl -s https://codecov.io/bash)

env:
    global:
        - TMPDIR=/tmp
