language: php

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=^2.8
    - php: 7.0
      env: SYMFONY_VERSION=^2.8
    - php: 7.1
      env: SYMFONY_VERSION=^2.8
    - php: 7.2
      env: SYMFONY_VERSION=^2.8
    - php: 5.6
      env: SYMFONY_VERSION=~3.0
    - php: 7.0
      env: SYMFONY_VERSION=~3.0
    - php: 7.1
      env: SYMFONY_VERSION=~3.0
    - php: 7.2
      env: SYMFONY_VERSION=~3.0
    - php: 7.1
      env: SYMFONY_VERSION=~4.0
    - php: 7.2
      env: SYMFONY_VERSION=~4.0

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update
  - php composer.phar update

script:
  - php -v
  - ./vendor/bin/phpcs --standard=psr2 DependencyInjection/ EventListener/ Provider/ Tests/SymfonyRollbarBundle
  - ./vendor/bin/phpunit -c Tests/phpunit.xml.dist

after_success:
    - bash <(curl -s https://codecov.io/bash)

env:
    global:
        - TMPDIR=/tmp
