language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php -v
  - ./vendor/bin/phpcs --standard=psr2 DependencyInjection/ EventListener/ Provider/ Tests/SymfonyRollbarBundle
  - ./vendor/bin/phpunit -c Tests/phpunit.xml.dist

after_success:
    - bash <(curl -s https://codecov.io/bash)

env:
    global:
        - secure: "r/35/U9I23Pt54pHDtGIluF4m+YFoRBcEi8vf0DqcZ+qMybThafvb1US5DTfvmIwnWkolc9sOdAZeAapM+0Q2SXJPIwS/JQMxHfvP6nqtZJxdLndYA6aBOJWcHWO5fL47UNMhfXrDtoqLYBkUS+VgqSTNktK/0z5Wm4P/dvMJBPBLb1waNiWC88MLmMzxU64iS7ypzCaw5Qa/vZ7JpmBVuC1aa++1+nJWc0FhT/ptSIggeBRtwyANpvIJifYNfU408eHRTJLBK3LrrgJeyc2U54JwSNQvtBcSPpb7aGNoBfzwpaRd8QoVuzL/LY1XRmedGRprVeY4eAiiHlZQLnR6KIiJFIuxN4Fpw3Vy9WddqjPmFM7JkG5iYu2iXjFVSAWO4gE2P9urZRTd+nsgBkV1Dv3cFEGftXmH+oH3tPzzmInzmlaNiHhs8MSiDvZv1oGPWdtWRAZVzJBxcofoM2GvDxj3NNQAAKWgHsbTb4eXZ3MMwdPbuYdJw/kT9uSPyqbK6zK1IzhrMZglBKZRDmlKelATRly6z2N8JNe0N5vckUYTLba9WcIt1BcaKYH5nIrNJJaYDqhBlSGaAsmwQhPsZN4AFRJzBHI+Bwc8DtxBLyQZC5wd6lL1G/fjHWQbYul6GPghTUR+W6ag/R17BiFjB+K5p1bK/vG9AWdeJjJDOE="
